# Generated by Django 3.0.8 on 2020-09-21 12:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('site', models.URLField()),
                ('image', models.ImageField(upload_to='images/infosite')),
                ('message', tinymce.models.HTMLField(verbose_name='Content')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Infosite',
                'verbose_name_plural': 'Infosites',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/Presentation')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('message_welcome', tinymce.models.HTMLField(verbose_name='Content')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
            },
        ),
    ]
